# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GdpMsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GdpMsg.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cGdpMsg.proto\"W\n\x06GdpMsg\x12\x11\n\tpacket_no\x18\x01 \x01(\x03\x12\x12\n\nnum_packet\x18\x02 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x15\n\rprotocol_type\x18\x04 \x01(\tb\x06proto3')
)




_GDPMSG = _descriptor.Descriptor(
  name='GdpMsg',
  full_name='GdpMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packet_no', full_name='GdpMsg.packet_no', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_packet', full_name='GdpMsg.num_packet', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='GdpMsg.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='protocol_type', full_name='GdpMsg.protocol_type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['GdpMsg'] = _GDPMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GdpMsg = _reflection.GeneratedProtocolMessageType('GdpMsg', (_message.Message,), dict(
  DESCRIPTOR = _GDPMSG,
  __module__ = 'GdpMsg_pb2'
  # @@protoc_insertion_point(class_scope:GdpMsg)
  ))
_sym_db.RegisterMessage(GdpMsg)


# @@protoc_insertion_point(module_scope)
